### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by marksev1** [lmartinking/webscreensaver#14]
What am i doing wrong?

 msev  ~  xscreensaver-demo
Traceback (most recent call last):
  File "/usr/lib/xscreensaver/webscreensaver", line 27, in <module>
    import gi
ImportError: No module named gi
Traceback (most recent call last):
  File "/usr/lib/xscreensaver/webscreensaver", line 27, in <module>
    import gi
ImportError: No module named gi

**Comment by lmartinking** [comment]
Hi there, looks like you're missing the gobject introspection python module.

Try this:

```
sudo apt install python-gi
```
